[workspace]
members = [
    "admin_authority",
    "token_authority_core",
    "token_authority_sdk",
    "examples",
    "methods",
    "integration_tests",
]
exclude = [
    "methods/guest",
]
resolver = "2"

[workspace.package]
version    = "0.1.0"
edition    = "2021"
license    = "MIT OR Apache-2.0"

[workspace.dependencies]
borsh       = { version = "1", features = ["derive"] }
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"
thiserror   = "2"
risc0-zkvm  = { version = "=3.0.5", features = ["std"] }
nssa        = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0-rc3", features = ["prove", "test-utils"] }
nssa_core   = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0-rc3", features = ["host"] }
admin_authority       = { path = "admin_authority" }
token_authority_core  = { path = "token_authority_core" }
token_authority_sdk   = { path = "token_authority_sdk" }
