[package]
name = "integration_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
lee        = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", rev = "a58fbce2ff48c58b7bb5001b1a27e64b9596ee3a", features = ["prove", "test-utils"] }
lee_core   = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", rev = "a58fbce2ff48c58b7bb5001b1a27e64b9596ee3a", features = ["host"] }
token-authority-methods = { path = "../methods" }
admin_authority         = { path = "../admin_authority" }
token_authority_core    = { path = "../token_authority_core" }
borsh      = { version = "1", features = ["derive"] }
serde      = { version = "1", features = ["derive"] }
